version: "3.9"

services:
  db:
    image: mysql:8
    container_name: tasks_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tasks_db
    volumes:
      - db_data:/var/lib/mysql
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - tasks_network

  api:
    build: ./backend
    container_name: tasks_api
    restart: always
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: tasks_db
    depends_on:
      - db
    ports:
      - "3000:3000"
    networks:
      - tasks_network

  nginx:
    image: nginx:alpine
    container_name: tasks_nginx
    ports:
      - "5000:80"
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api
    networks:
      - tasks_network

networks:
  tasks_network:

volumes:
  db_data:
